language: node_js
node_js:
  - "8"
env:
  - CXX=g++-4.8
addons:
  postgresql: "9.3"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - psql -c 'create database forum;' -U postgres
  - psql -c 'create database forum_test;' -U postgres
